name: 'Image Build: Heritrix'

on:
  push:
    branches:
      - main
      - 'initial-content'
    paths:
      - 'backstage-techdocs/**'
      - '.github/workflows/backstage-techdocs.yml'
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./backstage-techdocs
          file: ./backstage-techdocs/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/moving-shock/backstage-techdocs:latest
            ghcr.io/moving-shock/backstage-techdocs:0.1.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
